### ISSUE TITLE
Script ends before setup is complete - no error messages

### ISSUE THREAD

**Issue by g-ali** [microsoft/AzStackHCISandbox#11]
Hi,

After successfully deploying the host using the Azure Portal method, as per instructions I ran the shortcut on the host desktop 'New-AzSHCI-Sandbox using PowerShell.

The scripts get executed, after almost 2 hours, I can see Admincenter configuration scripts running , the script window then closes without any errors.
However the expected shortcut for the Admincenter VM does not get created on the host desktop and when I log on to the Admincenter VM, I can see that it hasn't been joined to the domain.
Does a log file get created and stored somewhere so that I can check if there were any errors or do you know what the issue could be?

Any assistance would be appreciated, I've tried twice so far and I'm seeing the same issue both times.

Regards

**Comment by mgodfre3** [comment]
Run the script from PowerShell directly, and that should give you a reason as to why it failed. 
C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1

**Comment by g-ali** [comment]
Thanks. I have ran the script from PowerShell directly and can now see the error. The script stops as it cannot restart AzSHost2 due to an 'illegal operation attempted on a registry key marked for deletion. Screenshot of the full error is attached.

I'm doing some Googling, seems there are various causes for this error.
Can you please advise, thanks.

![Sandbox error](https://user-images.githubusercontent.com/49446142/157858010-bb769e2a-7f0a-4446-8528-0251f033005d.PNG)

**Comment by mgodfre3** [comment]
Ok researching issue and seeing what the problem is, thanks for the information.

**Comment by g-ali** [comment]
Hi,

Apologies for chasing, I'm sure you are extremely busy, have you had a chance to research the issue? Thanks

**Comment by mgodfre3** [comment]
Rebuilt some of the scripts and items, as well as added a new Registration Script.  The latest test I have run have not seen this issue. Can you redeploy and let me know if you still see this issue?

**Comment by g-ali** [comment]
Thanks, just tried again. Getting a different error now. Screenshot below.

![image](https://user-images.githubusercontent.com/49446142/158471720-69e7631a-b61e-4a2b-8294-186924e98575.png)

**Comment by mgodfre3** [comment]
@g-ali  Reach out to me michael.godfrey@microsoft.com and I will set up a meeting to discuss/troubleshoot with you. I cant recreate this issue and need to ensure a few things in your lab. Thanks.

**Comment by g-ali** [comment]
Hi Michael,
I have sent you an email as requested.
Thanks

**Comment by g-ali** [comment]
After the changes Michael made, deployment of nested Azure HCI stack has now completed successfully.
