### ISSUE TITLE
Unable to Register HCI Cluster

### ISSUE THREAD

**Issue by Chirag1233** [microsoft/AzStackHCISandbox#13]
Hi there,

I have tried registering using the steps provided in the scenario get started readme.md file. 

I am keep running in to this error: 

Failed to register with Azure for cluster: azstackcluster.contoso.com. Error: RemoteException: Failed to register. Couldn't generate self-signed certificate on node(s) AzSHOST1,AzSHOST2. Couldn't set and verify registration certificate on node(s) AzSHOST1,AzSHOST2. Make sure every clustered node is up and has Internet connectivity (at least outbound to Azure).

Any idea why this isn't working ? 

I have not change the password for any of the servers

**Comment by mgodfre3** [comment]
Did this happen with the Register-Cluster.ps1 that is located in the Sandbox folder? Or was this via PoSH or Windows Admin Center. This is not necessarily an issue with the HCI Sandbox but with the registration service, and therefore you could always file an incident with Support, but I will also check into this. Thanks.
