### ISSUE TITLE
Simulate RRAS and BGP on hardware

### ISSUE THREAD

**Issue by xzrian** [microsoft/AzStackHCISandbox#17]
Hi,

I have inquiry regarding SDN sandbox.
May i know this script can be tailored and use on on prem hardware for testing purpose?
currently i'm wondering how i can simulate BGP and RRAS on real hardware

**Comment by mgodfre3** [comment]
The sandbox ps1 can be used on physical hardware as a standalone script but it will deploy a nested environment just the same, and that was actually the original intent a few years ago. 

For this scenario, I would advise you to view the code and adapt it to run on different servers. In an HCI with SDN only the hosts are physical. The network controllers, MUX and gateways and would be vms. The bgp would typically be a core or spine/leaf router. In the nested lab we had to use rras or a Linux router to achieve this function. You can use windows rras of coarse but IMHO and in my real lab I use a router as that more closely simulates more common deployments.
