### ISSUE TITLE
DSC URI points to non-existent branch

### ISSUE THREAD

**Issue by jweerts** [microsoft/AzStackHCISandbox#19]
DSC URI "https://github.com/microsoft/AzStackHCISandbox/blob/Server2022Update/DSC/ashcihost.zip?raw=true" refers to branch 'Server2022Update" that does not exist. This leads to the deployment failing in Azure.

**Comment by mgodfre3** [comment]
Latest PR addresses this issue and corrected the DSC URI in the deploy.json. Please confirm, will also confirm with testing.

**Comment by jweerts** [comment]
Deployment went through just fine!
Thank you for the quick fix
