### ISSUE TITLE
New-AzSHCISandbox errors out due to empty MountedDrive variable

### ISSUE THREAD

**Issue by jweerts** [microsoft/AzStackHCISandbox#21]
Line 552: `[string]$MountedDrive = (Mount-VHD -Path $path -Passthru | Get-Disk | Get-Partition | Get-Volume).DriveLetter
` does not return anything, resulting in `$MountedDrive` being empty.

This leads to Line 661: `$PantherDir = Get-ChildItem -Path ($MountedDrive + ":\Windows")  -Filter "Panther"`  throwing an error and stopping the script.

Full error message: 
```Get-ChildItem : Cannot find path 'C:\AzHCI_Sandbox\AzSHCISandbox-main\:\Windows' because it does not exist.
Get-ChildItem : Cannot find path 'C:\AzHCI_Sandbox\AzSHCISandbox-main\:\Windows' because it does not exist.
At C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1:661 char:23
+ ... antherDir = Get-ChildItem -Path ($MountedDrive + ":\Windows")  -Filte ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\AzHCI_Sandbo...-main\:\Windows:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 ```

Getting value of `$MountedDrive` when at line 661 returns nothing:
```Hit Line breakpoint on 'C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1:661'
[DBG]: PS C:\AzHCI_Sandbox\AzSHCISandbox-main>> $MountedDrive


```

The VHD shows up in Disk Manager, just does not have a drive letter assigned to it
![image](https://user-images.githubusercontent.com/15075842/179268311-b74ba538-8b77-4287-93f3-9a1c20430e70.png)

**Comment by mgodfre3** [comment]
I actually believe the issue is the License Key, yeaterday i updated the VM image to use windows server 2022, but the config file is using the AVMA key for Server 2019. I am testing with the correct key and will do a PR once I have confirmed. Thanks

**Comment by jweerts** [comment]
Awesome, I'll keep an eye out for the PR and try it.
Thank you for looking into it!

**Comment by mgodfre3** [comment]
New PR corrects issue, please confirm but recent test all were successful.
