### ISSUE TITLE
Region selection in Register-Cluster.ps1

### ISSUE THREAD

**Issue by tksh164** [microsoft/AzStackHCISandbox#26]
Is the following code correct? If so, why we need Microsoft.DesktopVirtualization resource provider?

https://github.com/microsoft/AzStackHCISandbox/blob/526fee1ec9a22791d3eede61281ddff2bf6f9917/Sandbox/Register-Cluster.ps1#L35-L36

I'm guessing Microsoft.AzureStackHCI is the correct resource provider.

**Comment by mgodfre3** [comment]
Yeah, i used that code from another issue and forgot to replace the provider.

**Comment by tksh164** [comment]
@mgodfre3 Thanks. Create PR #27
