### ISSUE TITLE
Cannot Register the Stack HCI Cluster

### ISSUE THREAD

**Issue by ekramyelnaggar** [microsoft/AzStackHCISandbox#35]
Hi,
the HCI cluster was implemented successfuly and the WAC was registered successfuly, but when I tried to register the HCI cluster I face the following error: 

Couldn't register Azure Stack HCI. Review the error and then try again. Name: [azstackcluster.contoso.com](http://azstackcluster.contoso.com/) Error: Error: RemoteException: Failed to register. Couldn't generate self-signed certificate on node(s) . Couldn't set and verify registration certificate on node(s) AzSHOST1,AzSHOST2. Make sure every clustered node is up and has Internet connectivity (at least outbound to Azure).

I confirm that internet is allowed and both HCI nodes can reach internet without any issues.

**Comment by mgodfre3** [comment]
@ekramyelnaggar 
Did you happen to change the DNS settings on the Virtual Network that the Azure VM is connected to? This error indicates that the nodes (virtual in this case) could not connect to the internet to generate the Self Signed Certificates. Please run through the following steps to ensure the HCI VMs can connect to Azure. 

Failed to register. Couldn't generate self-signed certificate on node(s) {Node1,Node2}. Couldn't set and verify registration certificate on node(s) {Node1,Node2}
Failure state explanation:

During registration, each server in the cluster must be up and running with outbound internet connectivity to Azure. The Register-AzStackHCI cmdlet talks to all servers in the cluster to provision certificates for each. Each server will use its certificate to make API call to HCI services in the cloud to validate registration.

If registration fails, you may see the following message: Failed to register. Couldn't generate self-signed certificate on node(s) {Node1,Node2}. Couldn't set and verify registration certificate on node(s) {Node1,Node2}

If there are node names after the Couldn't generate self-signed certificate on node(s) part of the error message, then the system wasn't able to generate the certificate on those server(s).

Remediation action:

Check that each server listed in the above message is up and running. You can check the status of hcisvc by running sc.exe query hcisvc and start it if needed with start-service hcisvc.

Check that each server listed in the error message has connectivity to the machine on which the Register-AzStackHCI cmdlet is run. Verify this by running the following cmdlet from the machine on which Register-AzStackHCI is run, using New-PSSession to connect to each server in the cluster and make sure it works:

PowerShell

Copy
New-PSSession -ComputerName {failing nodes}
If there are node names after the Couldn't set and verify registration certificate on node(s) part of the error message, then the service was able to generate the certificate on the server(s), but the server(s) weren't able to successfully call the HCI cloud service API. To troubleshoot:

Make sure each server has the required internet connectivity to talk to Azure Stack HCI cloud services and other required Azure services like Azure Active Directory, and that it's not being blocked by firewall(s). See [Firewall requirements for Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements).

Try running the Test-AzStackHCIConnection cmdlet and make sure it succeeds. This cmdlet invokes the health endpoint of HCI cloud services to test connectivity.

Look at the hcisvc debug logs on each node listed in the error message.

It's OK to have the message ExecuteWithRetry operation AADTokenFetch failed with retryable error appear a few times before it either fails with ExecuteWithRetry operation AADTokenFetch failed after all retries or ExecuteWithRetry operation AADTokenFetch succeeded in retry.
If you encounter ExecuteWithRetry operation AADTokenFetch failed after all retries in the logs, the system wasn't able to fetch the Azure Active Directory token from the service even after all the retries. There will be an associated Azure AD exception that's logged with this message.
If you see AADSTS700027: Client assertion contains an invalid signature. [Reason - The key used is expired. Thumbprint of key used by client: '{SomeThumbprint}', Found key 'Start=06/29/2021 21:13:15, End=06/29/2023 21:13:15', this is an issue with how the time is set on the server. Check the UTC time on all servers by running [System.DateTime]::UtcNow in PowerShell, and compare it with the actual UTC time. If the time isn't correct, then set the correct the times on the servers and then try registration again.
