### ISSUE TITLE
Error while deploying azure VM - VM has reported a failure when processing extension 'ConfigureAzSHCIHost'. Error message: \"DSC Configuration 'AzSHCIHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The term 'Get-MSCatalogUpdate' is not recognized as the name of a cmdlet, function, script file, or operable program. 

### ISSUE THREAD

**Issue by indiratechno** [microsoft/AzStackHCISandbox#37]
Deployment failed but I was able to connect to VM through remote desktop by downloading .rdp file .Can anyone please help me out  to sort the issue.

**Comment by mgodfre3** [comment]
This Code is not being maintained anymore, please switch the  JumpstartHCIBox for the deployments, as that is this code, updated to the latest feature sets. https://github.com/microsoft/azure_arc/blob/main/docs/azure_jumpstart_hcibox/_index.md

**Comment by indiratechno** [comment]
@mgodfre3 Thanks for the update
