### ISSUE TITLE
Template deployment failing - failed to execute Set-TargetResource functionality with error message: The term 'Get-MSCatalogUpdate' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by WVDAdminTF** [microsoft/AzStackHCISandbox#38]
Hello,

The template deployment is failing with below error, please advice

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'ConfigureAzSHCIHost'. Error message: \"DSC Configuration 'AzSHCIHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The term 'Get-MSCatalogUpdate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.  PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The term 'Get-MSCatalogUpdate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "}]}

![image_2023-02-02_201535885](https://user-images.githubusercontent.com/84956733/216356001-8e5fdeea-0596-4aa7-8aee-6a0ca5e0e11e.png)

Regards,
WVDAdminTF

**Comment by mgodfre3** [comment]
This deployment code is no longer being maintined in favor of the Jumpstart HCIBox. Please use that process now, as mentioned in the Readme in this Repo. https://github.com/microsoft/azure_arc/blob/main/docs/azure_jumpstart_hcibox/_index.md

Thanks.
