### ISSUE TITLE
Stack HCI SandBox deployment fails

### ISSUE THREAD

**Issue by xsayox** [microsoft/AzStackHCISandbox#39]
Hello. thank you always.
When I tried to create a Stack HCI verification environment on Azure using the code provided here, it fails when running PowerShell after VM deployment.

I got the following error message, is there any way to fix it?
----------
PS C:\AzHCI_Sandbox\AzSHCISandbox-main> & C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1 VERBOSE: Enabling PS Remoting on client... VERBOSE: Performing simple validation of Product Keys VERBOSE: No Multiple Hyper-V Hosts defined. Using Single Hyper-V Host Installation VERBOSE: Testing VHDX Path VERBOSE: Generating Single Host Placement
VERBOSE: Creating Internal Switch
VERBOSE: Creating NAT Switch
VERBOSE: Creating Internal NAT Switch: Internal NAT
VERBOSE: Applying IP Address to NAT Switch: Internal NAT
VERBOSE: Creating new NET NAT
VERBOSE: Getting local Parent VHDX Path
VERBOSE: Configuring Hyper-V Settings on localhost
VERBOSE: Copying VHDX Files to Host
VERBOSE: Copying C:\AzHCIVHDs\gui.vhdx to V:\VMs\GUI.VHDX
VERBOSE: Copying C:\AzHCIVHDs\azshci.vhdx to V:\VMs\AzSHCI.VHDX
VERBOSE: Generating the VM: @{AzSHOST=AzSMGMT; VMHost=ASHCIHost001}
VERBOSE: Virtual Machine FABRIC NIC MAC is = xx-xx-xx-xx-xx-xx
VERBOSE: Returned VMMac is xx-xx-xx-xx-xx-xx
VERBOSE: Generating the VM: @{AzSHOST=AzSHOST1; VMHost=ASHCIHost001}
VERBOSE: Virtual Machine FABRIC NIC MAC is = xx-xx-xx-xx-xx-yy
VERBOSE: Returned VMMac is xx-xx-xx-xx-xx-yy
VERBOSE: Generating the VM: @{AzSHOST=AzSHOST2; VMHost=ASHCIHost001}
VERBOSE: Virtual Machine FABRIC NIC MAC is = xx-xx-xx-xx-xx-zz
VERBOSE: Returned VMMac is xx-xx-xx-xx-xx-zz
VERBOSE: Performing offline installation of Hyper-V to path \\ASHCIHost001\V$\VMs\AzSMGMT.vhdx
VERBOSE: Installation started...
Install-WindowsFeature : The request to list features available on the specified server failed.
The image could not be mounted.
The I/O operation has been aborted because of either a thread exit or an application request. Error: 0x800703e3
At C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1:545 char:9
+ Install-WindowsFeature -Vhd $path -Name Hyper-V, RSAT-Hyper-V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~
     + CategoryInfo : InvalidOperation: (@{Vhd=\\ASHCIHo...Name=localhost}:PSObject) [Install-WindowsFeature],
     DeploymentProviderException
     + FullyQualifiedErrorId : DISMAPI_Error__Failed_To_Mount_Image,Microsoft.Windows.ServerManager.Commands.AddWindows
    Feature Command
----------

Thank you.
Sayo

**Comment by mgodfre3** [comment]
Thanks Sayo, this repo is no longer being maintained and I have redirected all the new code into the Jumpstart HCIBox. Please use that to deploy the latest version of the HCIBox to evaluate all aspects of Azure Stack HCI and Azure Arc Hybrid Solutions. Thanks for your interest and time.

**Comment by xsayox** [comment]
Thank you mgodfre3 for your reply.
I will try to build a jump start HCI Box as you taught me.
thank you.
