### ISSUE TITLE
blob where VHDX files are stored not accessible 

### ISSUE THREAD

**Issue by BartRoels** [microsoft/AzStackHCISandbox#4]
Seems that both URI's to the two VHDX files are unavailable.
https://aka.ms/AAbbhkn
https://aka.ms/AAbclsv

**Comment by mgodfre3** [comment]
Looking at this now, thanks for the heads up.

**Comment by mgodfre3** [comment]
This has been corrected, please test @BartRoels  and confirm it is working as expected. Then I will close this issue. Thanks.

**Comment by mgodfre3** [comment]
Confirmed links are working and access to VHDs was restored. Closing Issue. Thanks.
