### ISSUE TITLE
Failed to restart the AZHOST2

### ISSUE THREAD

**Issue by NakayamaKento** [microsoft/AzStackHCISandbox#6]
I have found the new issue about rebooting the AZHOST2.
This is related New-AzSHCISandbox.ps1:2718
`Restart-Computer $AzSHOST -Force -Confirm:$false -Credential $using:domainCred`

![image](https://user-images.githubusercontent.com/40586116/150730172-e4209e26-d4e0-4c24-9c58-3dc50de3e95f.png)

VERBOSE: Rebooting SDN Host AzSHOST2
Failed to restart the computer AzSHOST2 with the following error message: Illegal operation attempted on a registry key that has been 
marked for deletion. (Exception from HRESULT: 0x800703FA).
At C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1:2588 char:5
+     Invoke-Command -ComputerName Admincenter -Credential $domainCred  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (AzSHOST2:String) [Restart-Computer], InvalidOperationException
    + FullyQualifiedErrorId : RestartcomputerFailed,Microsoft.PowerShell.Commands.RestartComputerCommand
    + PSComputerName        : Admincenter #

**Comment by mgodfre3** [comment]
Ran another test fix, this has been resolved and tested. You will either need to delete the deployment, and the source files to ensure you get a recent update, or delete the Resource Group Deployment and redeploy entirely.
